ServerName localhost
<VirtualHost *:80>
    DocumentRoot /var/www/html/public
    <Directory /var/www/html/public>
        Options -Indexes -MultiViews
        AllowOverride FileInfo
        Require all granted
        DirectoryIndex index.php
    </Directory>
    <Directory /var/www/html/public/uploads>
        Require all denied
    </Directory>
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
