date.timezone=Asia/Ho_Chi_Minh
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
expose_php=Off
upload_max_filesize=20M
post_max_size=24M
memory_limit=256M
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax
session.gc_maxlifetime=28800
